language: node_js

node_js:
  - 12
  - 10

branches:
  only:
    - master

stages:
  - test
  - name: release
    if: type != pull_request AND branch = master

jobs:
  include:
    - stage: release
      script:
        - npm install --no-save conventional-changelog-eslint
        - npx semantic-release
